# Generated by Django 4.0.3 on 2022-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_reg_date',
            field=models.DateField(auto_now=True),
        ),
    ]
