# Generated by Django 4.0.3 on 2022-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainModel',
            fields=[
                ('cap_id', models.AutoField(primary_key=True, serialize=False)),
                ('cap_name', models.CharField(max_length=100)),
                ('cap_mobile', models.BigIntegerField()),
                ('cap_email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('cap_vehicle', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('con_pwd', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
            ],
            options={
                'db_table': 'captain_details',
            },
        ),
        migrations.DeleteModel(
            name='CaptainRegistrationModel',
        ),
    ]
